spring.application.name=primo-progetto

# Configurazione del server
server.port=8081
# con questo espongo tutti gli endpoint di Actuator, altrimenti posso scegliere quali esporre, come la riga sotto
management.endpoints.web.exposure.include=*
# management.endpoints.web.exposure.include=health,info

# questo non mi ricordo a che serve
management.info.env.enabled=true

# info a caso
info.app.author=Andrea Mirto
app.name=Academy App
app.version=1.0.0
app.welcome-msg=Benvenuto nella mia applicazione Spring Boot!

spring.profiles.active=dev
# per cambiare profili e "prendere" l'application.properties inerente al profilo selezionato, basta modificare questa riga, ad esempio mettendo "prod" al posto di "dev"