spring.application.name=esercizio

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/esercizioJPA?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings for automatic schema creation
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Use MySQL dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Spring Data REST properties: per le rest api
# spring.data.rest.base-path=/api

# custom path per swagger (non so se serve il .html, vedremo)
springdoc.swagger-ui.path=/swagger

# custom path per API docs (così per il json, con .yaml per lo yaml)
springdoc.api-docs.path=/apidocs

# impostazione di Jacskon per produrre i json: non mandare i valori nulli
spring.jackson.default-property-inclusion=non_null

# impostazione per ridurre il logging e tenere solo i warn
logging.level.root=warn

# spring security impostazione per vedere solo i log
logging.level.org.springframework.security=debug


# RICHIESTO DALL'ESERCIZIO
# ricrea il database ad ogni avvio dell'applicazione, cancellando i dati precedenti
spring.jpa.hibernate.ddl-auto=create-drop
